#!/usr/bin/env python3
# Copyright 2025-2026 Patrick J. Scruggs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Check documentation in every tracked Go source directory and module."""

import argparse
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile


def tracked(pattern):
    output = subprocess.check_output(['git', 'ls-files', '-z', pattern])
    return [pathlib.PurePosixPath(p.decode()) for p in output.split(b'\0') if p]


def module_for(path, modules):
    for parent in path.parents:
        if parent / 'go.mod' in modules:
            return parent
    raise RuntimeError(f'No tracked Go module owns {path}')


def json_stream(data):
    decoder = json.JSONDecoder()
    while data.strip():
        value, consumed = decoder.raw_decode(data.lstrip())
        yield value
        data = data.lstrip()[consumed:]


def check_e2e(root, binary, files):
    """Lint staged service modules using their checked-in module generator."""
    source = root / '.e2e/services'
    services = {
        'harness': source / 'e2e-harness',
        'core': source / 'target-apps/core-logging-target-app',
        'http': source / 'target-apps/trace-downstream-http',
        'grpc': source / 'target-apps/trace-downstream-grpc',
        'target': source / 'target-apps/trace-target-app',
    }
    generated = {p for p in files if p.parts[:3] == ('.e2e', 'services', 'traceproto')}
    for path in generated:
        marker = (b'Code generated by protoc-gen-go-grpc. DO NOT EDIT.'
                  if path.name == 'trace_grpc.pb.go' else
                  b'Code generated by protoc-gen-go. DO NOT EDIT.')
        if marker not in (root / path).read_bytes():
            raise RuntimeError(f'Generated-code exception lost its marker: {path}')
    if len(generated) != 2:
        raise RuntimeError(f'Expected two generated protobuf files, found {len(generated)}')

    version_source = (root / 'version.go').read_text()
    match = re.search(r'^var Version = "(v\d+\.\d+\.\d+)"', version_source, re.M)
    if not match:
        raise RuntimeError('Cannot determine core Version for E2E module generation')
    go_version = subprocess.check_output(['go', 'env', 'GOVERSION'], text=True).strip().removeprefix('go')

    with tempfile.TemporaryDirectory(prefix='godoclint-e2e-') as temporary:
        stage = pathlib.Path(temporary)
        for name, path in services.items():
            destination = stage / name
            shutil.copytree(path, destination)
            if name in ('harness', 'grpc', 'target'):
                shutil.copytree(source / 'traceproto', destination / 'traceproto')
            if name != 'harness':
                shutil.copytree(root, destination / 'slogcp',
                                ignore=shutil.ignore_patterns('.git', '.github', '.e2e',
                                                               '.examples', '.benchmarks', 'scratch'))

        command = [sys.executable, str(root / '.e2e/scripts/generate_go_module.py')]
        for name in services:
            command.extend(['--module-dir', str(stage / name)])
        command.extend(['--go-version', go_version, '--slogcp-dir', str(root),
                        '--slogcp-reference', match.group(1), '--dependency-mode', 'floor',
                        '--slogcp-shared-parity-scope', 'package'])
        subprocess.run(command, cwd=root, check=True)

        staged = {}
        for path in files - generated:
            for name, service in services.items():
                try:
                    relative = path.relative_to(service.relative_to(root))
                except ValueError:
                    continue
                staged[path] = (stage / name / relative).resolve()
                if (root / path).read_bytes() != staged[path].read_bytes():
                    raise RuntimeError(f'Staged E2E source differs from tracked file: {path}')
                break
        if set(staged) != files - generated:
            raise RuntimeError(f'Unstaged E2E files: {sorted(files - generated - set(staged))}')

        included = set()
        for name in services:
            directory = stage / name
            listing = subprocess.check_output(['go', 'list', '-json', './...'], cwd=directory, text=True)
            for package in json_stream(listing):
                package_dir = pathlib.Path(package['Dir'])
                for key in ('GoFiles', 'CgoFiles', 'TestGoFiles', 'XTestGoFiles'):
                    included.update((package_dir / file).resolve() for file in package.get(key, []))
            subprocess.run([str(binary), '-config', str(root / '.godoc-lint.yaml'), './...'],
                           cwd=directory, check=True)
        if not set(staged.values()) <= included:
            raise RuntimeError(f'E2E files missed by Go packages: '
                               f'{sorted(set(staged.values()) - included)}')

    print(f'Godoc-Lint checked {len(staged)} staged E2E Go files; '
          f'{len(generated)} generated protobuf files verified and exempted.')
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('godoclint', help='path to the pinned standalone godoclint binary')
    args = parser.parse_args()
    root = pathlib.Path.cwd()
    binary = pathlib.Path(args.godoclint).resolve()
    files = tracked('*.go')
    modules = set(tracked('*go.mod'))
    if not files:
        raise RuntimeError('No tracked Go files')
    e2e = {path for path in files if path.parts[0] == '.e2e'}
    groups = {}
    for path in set(files) - e2e:
        module = module_for(path, modules)
        groups.setdefault((module, path.parent), []).append(path)

    checked = set()
    for (module, directory), members in sorted(groups.items()):
        workdir = root / module
        package = '.' if directory == module else './' + directory.relative_to(module).as_posix()
        listing = subprocess.run(['go', 'list', '-json', package], cwd=workdir,
                                 text=True, capture_output=True, check=True)
        info = json.loads(listing.stdout)
        included = set(info.get('GoFiles', []) + info.get('CgoFiles', []) +
                       info.get('TestGoFiles', []) + info.get('XTestGoFiles', []))
        ignored = set(info.get('IgnoredGoFiles', []))
        expected = {p.name for p in members}
        missing = expected - included - ignored
        if missing:
            raise RuntimeError(f'{directory}: unlisted Go files: {sorted(missing)}')

        subprocess.run([str(binary), '-config', str(root / '.godoc-lint.yaml'), package],
                       cwd=workdir, check=True)
        checked.update(p for p in members if p.name in included)
        # Re-run packages for inactive platform files under their target GOOS.
        # Package analysis preserves referenced declarations in other files.
        for path in members:
            if path.name in ignored:
                if path.name.endswith('_linux.go'):
                    target_os = 'linux'
                    environment = dict(os.environ, GOOS=target_os)
                elif path.name.endswith('_other.go'):
                    target_os = 'windows'
                    environment = dict(os.environ, GOOS=target_os)
                elif b'//go:build benchmarks' in (root / path).read_bytes().splitlines()[:20]:
                    target_os = 'benchmarks tag'
                    environment = dict(os.environ)
                    environment['GOFLAGS'] = (environment.get('GOFLAGS', '') + ' -tags=benchmarks').strip()
                else:
                    raise RuntimeError(f'Unrecognized inactive Go file: {path}')
                alternative = subprocess.run(['go', 'list', '-json', package], cwd=workdir,
                                             env=environment, text=True, capture_output=True, check=True)
                alternative_files = json.loads(alternative.stdout)
                active = set(alternative_files.get('GoFiles', []) +
                             alternative_files.get('TestGoFiles', []) +
                             alternative_files.get('XTestGoFiles', []))
                if path.name not in active:
                    raise RuntimeError(f'{path} not active under GOOS={target_os}')
                subprocess.run([str(binary), '-config', str(root / '.godoc-lint.yaml'),
                                package], cwd=workdir, env=environment, check=True)
                checked.add(path)

    checked.update(check_e2e(root, binary, e2e))
    if checked != set(files):
        raise RuntimeError(f'Coverage mismatch: {sorted(set(files) - checked)}')
    print(f'Coverage accounted for all {len(files)} tracked Go files in '
          f'{len(groups)} source directories across {len({k[0] for k in groups})} '
          'checked-in modules plus the staged E2E modules.')


if __name__ == '__main__':
    try:
        main()
    except (subprocess.CalledProcessError, RuntimeError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
