// Copyright 2025-2026 Patrick J. Scruggs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: trace.proto

package tracepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceWorkRequest) Reset() {
	*x = TraceWorkRequest{}
	mi := &file_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceWorkRequest) ProtoMessage() {}

func (x *TraceWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceWorkRequest.ProtoReflect.Descriptor instead.
func (*TraceWorkRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{0}
}

func (x *TraceWorkRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TraceWorkRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TraceWorkResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledgement string                 `protobuf:"bytes,1,opt,name=acknowledgement,proto3" json:"acknowledgement,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TraceWorkResponse) Reset() {
	*x = TraceWorkResponse{}
	mi := &file_trace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceWorkResponse) ProtoMessage() {}

func (x *TraceWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceWorkResponse.ProtoReflect.Descriptor instead.
func (*TraceWorkResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{1}
}

func (x *TraceWorkResponse) GetAcknowledgement() string {
	if x != nil {
		return x.Acknowledgement
	}
	return ""
}

func (x *TraceWorkResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ErrorWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	GrpcStatus    string                 `protobuf:"bytes,2,opt,name=grpc_status,json=grpcStatus,proto3" json:"grpc_status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorWorkRequest) Reset() {
	*x = ErrorWorkRequest{}
	mi := &file_trace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorWorkRequest) ProtoMessage() {}

func (x *ErrorWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorWorkRequest.ProtoReflect.Descriptor instead.
func (*ErrorWorkRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorWorkRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ErrorWorkRequest) GetGrpcStatus() string {
	if x != nil {
		return x.GrpcStatus
	}
	return ""
}

func (x *ErrorWorkRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PanicWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	PanicMessage  string                 `protobuf:"bytes,2,opt,name=panic_message,json=panicMessage,proto3" json:"panic_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanicWorkRequest) Reset() {
	*x = PanicWorkRequest{}
	mi := &file_trace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanicWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanicWorkRequest) ProtoMessage() {}

func (x *PanicWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanicWorkRequest.ProtoReflect.Descriptor instead.
func (*PanicWorkRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{3}
}

func (x *PanicWorkRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *PanicWorkRequest) GetPanicMessage() string {
	if x != nil {
		return x.PanicMessage
	}
	return ""
}

type EchoPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoPayloadRequest) Reset() {
	*x = EchoPayloadRequest{}
	mi := &file_trace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoPayloadRequest) ProtoMessage() {}

func (x *EchoPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoPayloadRequest.ProtoReflect.Descriptor instead.
func (*EchoPayloadRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{4}
}

func (x *EchoPayloadRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *EchoPayloadRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type EchoPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoPayloadResponse) Reset() {
	*x = EchoPayloadResponse{}
	mi := &file_trace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoPayloadResponse) ProtoMessage() {}

func (x *EchoPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoPayloadResponse.ProtoReflect.Descriptor instead.
func (*EchoPayloadResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{5}
}

func (x *EchoPayloadResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ServerStreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TestId          string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ResponseCount   int32                  `protobuf:"varint,2,opt,name=response_count,json=responseCount,proto3" json:"response_count,omitempty"`
	ResponsePayload string                 `protobuf:"bytes,3,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	FinalStatus     string                 `protobuf:"bytes,4,opt,name=final_status,json=finalStatus,proto3" json:"final_status,omitempty"`
	FinalMessage    string                 `protobuf:"bytes,5,opt,name=final_message,json=finalMessage,proto3" json:"final_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerStreamRequest) Reset() {
	*x = ServerStreamRequest{}
	mi := &file_trace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRequest) ProtoMessage() {}

func (x *ServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{6}
}

func (x *ServerStreamRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ServerStreamRequest) GetResponseCount() int32 {
	if x != nil {
		return x.ResponseCount
	}
	return 0
}

func (x *ServerStreamRequest) GetResponsePayload() string {
	if x != nil {
		return x.ResponsePayload
	}
	return ""
}

func (x *ServerStreamRequest) GetFinalStatus() string {
	if x != nil {
		return x.FinalStatus
	}
	return ""
}

func (x *ServerStreamRequest) GetFinalMessage() string {
	if x != nil {
		return x.FinalMessage
	}
	return ""
}

type ServerStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamResponse) Reset() {
	*x = ServerStreamResponse{}
	mi := &file_trace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamResponse) ProtoMessage() {}

func (x *ServerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamResponse.ProtoReflect.Descriptor instead.
func (*ServerStreamResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{7}
}

func (x *ServerStreamResponse) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ServerStreamResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ServerStreamResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ClientStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ChunkId       string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	FinalStatus   string                 `protobuf:"bytes,4,opt,name=final_status,json=finalStatus,proto3" json:"final_status,omitempty"`
	FinalMessage  string                 `protobuf:"bytes,5,opt,name=final_message,json=finalMessage,proto3" json:"final_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamRequest) Reset() {
	*x = ClientStreamRequest{}
	mi := &file_trace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamRequest) ProtoMessage() {}

func (x *ClientStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{8}
}

func (x *ClientStreamRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ClientStreamRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ClientStreamRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ClientStreamRequest) GetFinalStatus() string {
	if x != nil {
		return x.FinalStatus
	}
	return ""
}

func (x *ClientStreamRequest) GetFinalMessage() string {
	if x != nil {
		return x.FinalMessage
	}
	return ""
}

type ClientStreamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestId         string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ReceivedChunks int32                  `protobuf:"varint,2,opt,name=received_chunks,json=receivedChunks,proto3" json:"received_chunks,omitempty"`
	Concatenated   string                 `protobuf:"bytes,3,opt,name=concatenated,proto3" json:"concatenated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientStreamResponse) Reset() {
	*x = ClientStreamResponse{}
	mi := &file_trace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResponse) ProtoMessage() {}

func (x *ClientStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{9}
}

func (x *ClientStreamResponse) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ClientStreamResponse) GetReceivedChunks() int32 {
	if x != nil {
		return x.ReceivedChunks
	}
	return 0
}

func (x *ClientStreamResponse) GetConcatenated() string {
	if x != nil {
		return x.Concatenated
	}
	return ""
}

type BidiStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ChunkId       string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CloseAfter    bool                   `protobuf:"varint,4,opt,name=close_after,json=closeAfter,proto3" json:"close_after,omitempty"`
	FinalStatus   string                 `protobuf:"bytes,5,opt,name=final_status,json=finalStatus,proto3" json:"final_status,omitempty"`
	FinalMessage  string                 `protobuf:"bytes,6,opt,name=final_message,json=finalMessage,proto3" json:"final_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiStreamRequest) Reset() {
	*x = BidiStreamRequest{}
	mi := &file_trace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiStreamRequest) ProtoMessage() {}

func (x *BidiStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiStreamRequest.ProtoReflect.Descriptor instead.
func (*BidiStreamRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{10}
}

func (x *BidiStreamRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *BidiStreamRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *BidiStreamRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *BidiStreamRequest) GetCloseAfter() bool {
	if x != nil {
		return x.CloseAfter
	}
	return false
}

func (x *BidiStreamRequest) GetFinalStatus() string {
	if x != nil {
		return x.FinalStatus
	}
	return ""
}

func (x *BidiStreamRequest) GetFinalMessage() string {
	if x != nil {
		return x.FinalMessage
	}
	return ""
}

type BidiStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ChunkId       string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiStreamResponse) Reset() {
	*x = BidiStreamResponse{}
	mi := &file_trace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiStreamResponse) ProtoMessage() {}

func (x *BidiStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiStreamResponse.ProtoReflect.Descriptor instead.
func (*BidiStreamResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{11}
}

func (x *BidiStreamResponse) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *BidiStreamResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *BidiStreamResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_trace_proto protoreflect.FileDescriptor

const file_trace_proto_rawDesc = "" +
	"\n" +
	"\vtrace.proto\x12\ttracegrpc\"E\n" +
	"\x10TraceWorkRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc2\x01\n" +
	"\x11TraceWorkResponse\x12(\n" +
	"\x0facknowledgement\x18\x01 \x01(\tR\x0facknowledgement\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.tracegrpc.TraceWorkResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x10ErrorWorkRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1f\n" +
	"\vgrpc_status\x18\x02 \x01(\tR\n" +
	"grpcStatus\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"P\n" +
	"\x10PanicWorkRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12#\n" +
	"\rpanic_message\x18\x02 \x01(\tR\fpanicMessage\"A\n" +
	"\x12EchoPayloadRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\")\n" +
	"\x13EchoPayloadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xc8\x01\n" +
	"\x13ServerStreamRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12%\n" +
	"\x0eresponse_count\x18\x02 \x01(\x05R\rresponseCount\x12)\n" +
	"\x10response_payload\x18\x03 \x01(\tR\x0fresponsePayload\x12!\n" +
	"\ffinal_status\x18\x04 \x01(\tR\vfinalStatus\x12#\n" +
	"\rfinal_message\x18\x05 \x01(\tR\ffinalMessage\"e\n" +
	"\x14ServerStreamResponse\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\xab\x01\n" +
	"\x13ClientStreamRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12!\n" +
	"\ffinal_status\x18\x04 \x01(\tR\vfinalStatus\x12#\n" +
	"\rfinal_message\x18\x05 \x01(\tR\ffinalMessage\"|\n" +
	"\x14ClientStreamResponse\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12'\n" +
	"\x0freceived_chunks\x18\x02 \x01(\x05R\x0ereceivedChunks\x12\"\n" +
	"\fconcatenated\x18\x03 \x01(\tR\fconcatenated\"\xca\x01\n" +
	"\x11BidiStreamRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1f\n" +
	"\vclose_after\x18\x04 \x01(\bR\n" +
	"closeAfter\x12!\n" +
	"\ffinal_status\x18\x05 \x01(\tR\vfinalStatus\x12#\n" +
	"\rfinal_message\x18\x06 \x01(\tR\ffinalMessage\"b\n" +
	"\x12BidiStreamResponse\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload2\xa4\x04\n" +
	"\vTraceWorker\x12C\n" +
	"\x06DoWork\x12\x1b.tracegrpc.TraceWorkRequest\x1a\x1c.tracegrpc.TraceWorkResponse\x12E\n" +
	"\bFailWork\x12\x1b.tracegrpc.ErrorWorkRequest\x1a\x1c.tracegrpc.TraceWorkResponse\x12F\n" +
	"\tPanicWork\x12\x1b.tracegrpc.PanicWorkRequest\x1a\x1c.tracegrpc.TraceWorkResponse\x12L\n" +
	"\vEchoPayload\x12\x1d.tracegrpc.EchoPayloadRequest\x1a\x1e.tracegrpc.EchoPayloadResponse\x12Q\n" +
	"\fStreamServer\x12\x1e.tracegrpc.ServerStreamRequest\x1a\x1f.tracegrpc.ServerStreamResponse0\x01\x12Q\n" +
	"\fStreamClient\x12\x1e.tracegrpc.ClientStreamRequest\x1a\x1f.tracegrpc.ClientStreamResponse(\x01\x12M\n" +
	"\n" +
	"StreamBidi\x12\x1c.tracegrpc.BidiStreamRequest\x1a\x1d.tracegrpc.BidiStreamResponse(\x010\x01B>Z<github.com/pjscruggs/slogcp-test/services/traceproto;tracepbb\x06proto3"

var (
	file_trace_proto_rawDescOnce sync.Once
	file_trace_proto_rawDescData []byte
)

func file_trace_proto_rawDescGZIP() []byte {
	file_trace_proto_rawDescOnce.Do(func() {
		file_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trace_proto_rawDesc), len(file_trace_proto_rawDesc)))
	})
	return file_trace_proto_rawDescData
}

var file_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_trace_proto_goTypes = []any{
	(*TraceWorkRequest)(nil),     // 0: tracegrpc.TraceWorkRequest
	(*TraceWorkResponse)(nil),    // 1: tracegrpc.TraceWorkResponse
	(*ErrorWorkRequest)(nil),     // 2: tracegrpc.ErrorWorkRequest
	(*PanicWorkRequest)(nil),     // 3: tracegrpc.PanicWorkRequest
	(*EchoPayloadRequest)(nil),   // 4: tracegrpc.EchoPayloadRequest
	(*EchoPayloadResponse)(nil),  // 5: tracegrpc.EchoPayloadResponse
	(*ServerStreamRequest)(nil),  // 6: tracegrpc.ServerStreamRequest
	(*ServerStreamResponse)(nil), // 7: tracegrpc.ServerStreamResponse
	(*ClientStreamRequest)(nil),  // 8: tracegrpc.ClientStreamRequest
	(*ClientStreamResponse)(nil), // 9: tracegrpc.ClientStreamResponse
	(*BidiStreamRequest)(nil),    // 10: tracegrpc.BidiStreamRequest
	(*BidiStreamResponse)(nil),   // 11: tracegrpc.BidiStreamResponse
	nil,                          // 12: tracegrpc.TraceWorkResponse.MetadataEntry
}
var file_trace_proto_depIdxs = []int32{
	12, // 0: tracegrpc.TraceWorkResponse.metadata:type_name -> tracegrpc.TraceWorkResponse.MetadataEntry
	0,  // 1: tracegrpc.TraceWorker.DoWork:input_type -> tracegrpc.TraceWorkRequest
	2,  // 2: tracegrpc.TraceWorker.FailWork:input_type -> tracegrpc.ErrorWorkRequest
	3,  // 3: tracegrpc.TraceWorker.PanicWork:input_type -> tracegrpc.PanicWorkRequest
	4,  // 4: tracegrpc.TraceWorker.EchoPayload:input_type -> tracegrpc.EchoPayloadRequest
	6,  // 5: tracegrpc.TraceWorker.StreamServer:input_type -> tracegrpc.ServerStreamRequest
	8,  // 6: tracegrpc.TraceWorker.StreamClient:input_type -> tracegrpc.ClientStreamRequest
	10, // 7: tracegrpc.TraceWorker.StreamBidi:input_type -> tracegrpc.BidiStreamRequest
	1,  // 8: tracegrpc.TraceWorker.DoWork:output_type -> tracegrpc.TraceWorkResponse
	1,  // 9: tracegrpc.TraceWorker.FailWork:output_type -> tracegrpc.TraceWorkResponse
	1,  // 10: tracegrpc.TraceWorker.PanicWork:output_type -> tracegrpc.TraceWorkResponse
	5,  // 11: tracegrpc.TraceWorker.EchoPayload:output_type -> tracegrpc.EchoPayloadResponse
	7,  // 12: tracegrpc.TraceWorker.StreamServer:output_type -> tracegrpc.ServerStreamResponse
	9,  // 13: tracegrpc.TraceWorker.StreamClient:output_type -> tracegrpc.ClientStreamResponse
	11, // 14: tracegrpc.TraceWorker.StreamBidi:output_type -> tracegrpc.BidiStreamResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_trace_proto_init() }
func file_trace_proto_init() {
	if File_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trace_proto_rawDesc), len(file_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trace_proto_goTypes,
		DependencyIndexes: file_trace_proto_depIdxs,
		MessageInfos:      file_trace_proto_msgTypes,
	}.Build()
	File_trace_proto = out.File
	file_trace_proto_goTypes = nil
	file_trace_proto_depIdxs = nil
}
