// Copyright 2025-2026 Patrick J. Scruggs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.3
// source: trace.proto

package tracepb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TraceWorker_DoWork_FullMethodName       = "/tracegrpc.TraceWorker/DoWork"
	TraceWorker_FailWork_FullMethodName     = "/tracegrpc.TraceWorker/FailWork"
	TraceWorker_PanicWork_FullMethodName    = "/tracegrpc.TraceWorker/PanicWork"
	TraceWorker_EchoPayload_FullMethodName  = "/tracegrpc.TraceWorker/EchoPayload"
	TraceWorker_StreamServer_FullMethodName = "/tracegrpc.TraceWorker/StreamServer"
	TraceWorker_StreamClient_FullMethodName = "/tracegrpc.TraceWorker/StreamClient"
	TraceWorker_StreamBidi_FullMethodName   = "/tracegrpc.TraceWorker/StreamBidi"
)

// TraceWorkerClient is the client API for TraceWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraceWorkerClient interface {
	DoWork(ctx context.Context, in *TraceWorkRequest, opts ...grpc.CallOption) (*TraceWorkResponse, error)
	FailWork(ctx context.Context, in *ErrorWorkRequest, opts ...grpc.CallOption) (*TraceWorkResponse, error)
	PanicWork(ctx context.Context, in *PanicWorkRequest, opts ...grpc.CallOption) (*TraceWorkResponse, error)
	EchoPayload(ctx context.Context, in *EchoPayloadRequest, opts ...grpc.CallOption) (*EchoPayloadResponse, error)
	StreamServer(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (TraceWorker_StreamServerClient, error)
	StreamClient(ctx context.Context, opts ...grpc.CallOption) (TraceWorker_StreamClientClient, error)
	StreamBidi(ctx context.Context, opts ...grpc.CallOption) (TraceWorker_StreamBidiClient, error)
}

type traceWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceWorkerClient(cc grpc.ClientConnInterface) TraceWorkerClient {
	return &traceWorkerClient{cc}
}

func (c *traceWorkerClient) DoWork(ctx context.Context, in *TraceWorkRequest, opts ...grpc.CallOption) (*TraceWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceWorkResponse)
	err := c.cc.Invoke(ctx, TraceWorker_DoWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceWorkerClient) FailWork(ctx context.Context, in *ErrorWorkRequest, opts ...grpc.CallOption) (*TraceWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceWorkResponse)
	err := c.cc.Invoke(ctx, TraceWorker_FailWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceWorkerClient) PanicWork(ctx context.Context, in *PanicWorkRequest, opts ...grpc.CallOption) (*TraceWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceWorkResponse)
	err := c.cc.Invoke(ctx, TraceWorker_PanicWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceWorkerClient) EchoPayload(ctx context.Context, in *EchoPayloadRequest, opts ...grpc.CallOption) (*EchoPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoPayloadResponse)
	err := c.cc.Invoke(ctx, TraceWorker_EchoPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceWorkerClient) StreamServer(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (TraceWorker_StreamServerClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TraceWorker_ServiceDesc.Streams[0], TraceWorker_StreamServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &traceWorkerStreamServerClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TraceWorker_StreamServerClient interface {
	Recv() (*ServerStreamResponse, error)
	grpc.ClientStream
}

type traceWorkerStreamServerClient struct {
	grpc.ClientStream
}

func (x *traceWorkerStreamServerClient) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *traceWorkerClient) StreamClient(ctx context.Context, opts ...grpc.CallOption) (TraceWorker_StreamClientClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TraceWorker_ServiceDesc.Streams[1], TraceWorker_StreamClient_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &traceWorkerStreamClientClient{ClientStream: stream}
	return x, nil
}

type TraceWorker_StreamClientClient interface {
	Send(*ClientStreamRequest) error
	CloseAndRecv() (*ClientStreamResponse, error)
	grpc.ClientStream
}

type traceWorkerStreamClientClient struct {
	grpc.ClientStream
}

func (x *traceWorkerStreamClientClient) Send(m *ClientStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *traceWorkerStreamClientClient) CloseAndRecv() (*ClientStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ClientStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *traceWorkerClient) StreamBidi(ctx context.Context, opts ...grpc.CallOption) (TraceWorker_StreamBidiClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TraceWorker_ServiceDesc.Streams[2], TraceWorker_StreamBidi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &traceWorkerStreamBidiClient{ClientStream: stream}
	return x, nil
}

type TraceWorker_StreamBidiClient interface {
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
	grpc.ClientStream
}

type traceWorkerStreamBidiClient struct {
	grpc.ClientStream
}

func (x *traceWorkerStreamBidiClient) Send(m *BidiStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *traceWorkerStreamBidiClient) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TraceWorkerServer is the server API for TraceWorker service.
// All implementations must embed UnimplementedTraceWorkerServer
// for forward compatibility
type TraceWorkerServer interface {
	DoWork(context.Context, *TraceWorkRequest) (*TraceWorkResponse, error)
	FailWork(context.Context, *ErrorWorkRequest) (*TraceWorkResponse, error)
	PanicWork(context.Context, *PanicWorkRequest) (*TraceWorkResponse, error)
	EchoPayload(context.Context, *EchoPayloadRequest) (*EchoPayloadResponse, error)
	StreamServer(*ServerStreamRequest, TraceWorker_StreamServerServer) error
	StreamClient(TraceWorker_StreamClientServer) error
	StreamBidi(TraceWorker_StreamBidiServer) error
	mustEmbedUnimplementedTraceWorkerServer()
}

// UnimplementedTraceWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedTraceWorkerServer struct {
}

func (UnimplementedTraceWorkerServer) DoWork(context.Context, *TraceWorkRequest) (*TraceWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoWork not implemented")
}
func (UnimplementedTraceWorkerServer) FailWork(context.Context, *ErrorWorkRequest) (*TraceWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailWork not implemented")
}
func (UnimplementedTraceWorkerServer) PanicWork(context.Context, *PanicWorkRequest) (*TraceWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PanicWork not implemented")
}
func (UnimplementedTraceWorkerServer) EchoPayload(context.Context, *EchoPayloadRequest) (*EchoPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoPayload not implemented")
}
func (UnimplementedTraceWorkerServer) StreamServer(*ServerStreamRequest, TraceWorker_StreamServerServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamServer not implemented")
}
func (UnimplementedTraceWorkerServer) StreamClient(TraceWorker_StreamClientServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamClient not implemented")
}
func (UnimplementedTraceWorkerServer) StreamBidi(TraceWorker_StreamBidiServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBidi not implemented")
}
func (UnimplementedTraceWorkerServer) mustEmbedUnimplementedTraceWorkerServer() {}

// UnsafeTraceWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraceWorkerServer will
// result in compilation errors.
type UnsafeTraceWorkerServer interface {
	mustEmbedUnimplementedTraceWorkerServer()
}

func RegisterTraceWorkerServer(s grpc.ServiceRegistrar, srv TraceWorkerServer) {
	s.RegisterService(&TraceWorker_ServiceDesc, srv)
}

func _TraceWorker_DoWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceWorkerServer).DoWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceWorker_DoWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceWorkerServer).DoWork(ctx, req.(*TraceWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceWorker_FailWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceWorkerServer).FailWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceWorker_FailWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceWorkerServer).FailWork(ctx, req.(*ErrorWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceWorker_PanicWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PanicWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceWorkerServer).PanicWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceWorker_PanicWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceWorkerServer).PanicWork(ctx, req.(*PanicWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceWorker_EchoPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceWorkerServer).EchoPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceWorker_EchoPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceWorkerServer).EchoPayload(ctx, req.(*EchoPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceWorker_StreamServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TraceWorkerServer).StreamServer(m, &traceWorkerStreamServerServer{ServerStream: stream})
}

type TraceWorker_StreamServerServer interface {
	Send(*ServerStreamResponse) error
	grpc.ServerStream
}

type traceWorkerStreamServerServer struct {
	grpc.ServerStream
}

func (x *traceWorkerStreamServerServer) Send(m *ServerStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TraceWorker_StreamClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TraceWorkerServer).StreamClient(&traceWorkerStreamClientServer{ServerStream: stream})
}

type TraceWorker_StreamClientServer interface {
	SendAndClose(*ClientStreamResponse) error
	Recv() (*ClientStreamRequest, error)
	grpc.ServerStream
}

type traceWorkerStreamClientServer struct {
	grpc.ServerStream
}

func (x *traceWorkerStreamClientServer) SendAndClose(m *ClientStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *traceWorkerStreamClientServer) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TraceWorker_StreamBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TraceWorkerServer).StreamBidi(&traceWorkerStreamBidiServer{ServerStream: stream})
}

type TraceWorker_StreamBidiServer interface {
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
	grpc.ServerStream
}

type traceWorkerStreamBidiServer struct {
	grpc.ServerStream
}

func (x *traceWorkerStreamBidiServer) Send(m *BidiStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *traceWorkerStreamBidiServer) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TraceWorker_ServiceDesc is the grpc.ServiceDesc for TraceWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraceWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracegrpc.TraceWorker",
	HandlerType: (*TraceWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoWork",
			Handler:    _TraceWorker_DoWork_Handler,
		},
		{
			MethodName: "FailWork",
			Handler:    _TraceWorker_FailWork_Handler,
		},
		{
			MethodName: "PanicWork",
			Handler:    _TraceWorker_PanicWork_Handler,
		},
		{
			MethodName: "EchoPayload",
			Handler:    _TraceWorker_EchoPayload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamServer",
			Handler:       _TraceWorker_StreamServer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamClient",
			Handler:       _TraceWorker_StreamClient_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamBidi",
			Handler:       _TraceWorker_StreamBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "trace.proto",
}
