# Copyright 2026 Patrick J. Scruggs
# SPDX-License-Identifier: Apache-2.0
steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, --tag, '${_IMAGE}', .]
images: ['${_IMAGE}']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 600s
