name: Go Format and Lint

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-format-lint.yml'
      - '.golangci.yml'
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  merge_group:
    types: [ checks_requested ]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  format-and-lint:
    name: ✨🧹 Format and Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 0 || 1 }}

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: ✨ Check Go Formatting
        id: gofmt-check
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          if [ -n "$(goimports -l $(find . -type f -name '*.go' | grep -v /vendor/))" ]; then
            echo "✨⚠️ Code formatting issues found. Please run 'goimports -local github.com/pjscruggs/slogcp -w .' locally."
            exit 1
          fi

      - name: 🧹 Run golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7
        with:
          version: latest
          args: --config=.golangci.yml
          only-new-issues: ${{ github.event_name == 'pull_request' }}