name: Fix License Headers

on:
  workflow_dispatch:

# Need write permissions to create commits
permissions:
  contents: write

jobs:
  fix-license-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      
      - name: Fix License Headers
        uses: apache/skywalking-eyes/header@5c5b974209f0de5d905f37deb69369068ebfc15c # v0.7.0
        with:
          mode: fix
          config: .licenserc.yaml
          
      - name: Commit changes if needed
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: License Bot
          author_email: license-bot@github.com
          message: 'chore: Update license headers'
          add: '.'