name: Weekly Maintenance

on:
  schedule:
    - cron: '0 1 * * 0' # Run at 1:00 UTC every Sunday
  workflow_dispatch:

# Apply least privilege principle
permissions:
  contents: read

jobs:
  license-header:
    name: License Check
    uses: ./.github/workflows/license-header.yml

  format-lint:
    name: Format & Lint
    needs: [license-header]
    uses: ./.github/workflows/go-format-lint.yml

  test:
    name: Tests
    needs: [format-lint]
    uses: ./.github/workflows/go-tests.yml

  vulnerability-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...